apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
  namespace: ingress-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: app-container
        image: djohnacademy/mini-project
        ports:
        - containerPort: 7681
        volumeMounts:
        - mountPath: /tmp
          name: data-volume
      - name: nginx-sidecar
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sidecar-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: app-pvc
      - name: sidecar-html
        configMap:
          name: sidecar-canary-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-canary-config
  namespace: ingress-nginx
data:
  index.html: |
    schedulerv2
