apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
